#include "GcodeGenerator.h"

#include <QLineF>
#include <QPointF>
#include <QStringList>
#include <QtMath>

namespace {
QString fmtMm(double v) {
    return QString::number(v, 'f', 3);
}

QString xyLine(const char *cmd, double xMm, double yMm) {
    return QStringLiteral("%1 X%2 Y%3").arg(QLatin1String(cmd), fmtMm(xMm), fmtMm(yMm));
}

QPointF layoutCmToMachineMm(const QPointF &pCm) {
    return QPointF(pCm.y() * 10.0, pCm.x() * 10.0);
}

double segmentLengthCm(const PathSegment &seg) {
    const QVector<QPointF> &pts = seg.pointsCm;
    if (pts.size() < 2) return 0;
    if (seg.travel) return QLineF(pts[0], pts[1]).length();
    double len = 0;
    for (int i = 1; i < pts.size(); ++i)
        len += QLineF(pts[i - 1], pts[i]).length();
    return len;
}

int maxPageInPath(const PathBuildResult &path) {
    int last = 0;
    for (const PathSegment &seg : path.segments)
        last = qMax(last, seg.pageIndex);
    return last;
}

double interpolateByY(double absYmm, double yStartMm, double yEndMm, double nearValue, double farValue) {
    const double span = yEndMm - yStartMm;
    double t = 0.0;
    if (span > 1e-9) {
        t = (absYmm - yStartMm) / span;
    } else {
        t = absYmm >= yEndMm ? 1.0 : 0.0;
    }
    t = qBound(0.0, t, 1.0);
    return nearValue + (farValue - nearValue) * t;
}
}

QString GcodeGenerator::generate(const PathBuildResult &path, const AppSettings *settings) {
    return generateWithPageLines(path, settings).gcode;
}

GcodeGenerateResult GcodeGenerator::generateWithPageLines(const PathBuildResult &path,
                                                          const AppSettings *settings) {
    GcodeGenerateResult out;
    if (!settings) {
        out.gcode = QStringLiteral("; No settings\n");
        return out;
    }

    const double penUpZ = settings->penUpZ();
    const double penDownZ = settings->penDownZ();
    const int feed = qMax(1, int(qRound(settings->feedRateMmPerMin())));

    QStringList lines;
    lines << QStringLiteral("; GRBL 1.1h — generated by WriterQt");
    lines << QStringLiteral("; Units: mm, absolute positioning");
    lines << QStringLiteral("G21");
    lines << QStringLiteral("G90");
    lines << QStringLiteral("G0 Z%1").arg(fmtMm(penUpZ));
    lines << QStringLiteral("G0 X0 Y0");
    lines << QStringLiteral("F%1").arg(feed);

    const int pageCount = qMax(1, maxPageInPath(path) + 1);
    out.pageCount = pageCount;
    out.pageLineStart.resize(pageCount);
    for (int i = 0; i < pageCount; ++i)
        out.pageLineStart[i] = -1;

    bool hasMotion = false;
    bool penIsDown = false;
    bool hasPos = false;
    QPointF currentPosMm;
    const double joinDistMm = qMax(0.0, settings->joinDistMm());
    const double yStartMm = qMax(0.0, settings->backlashYStartMm());
    const double yEndMm = qMax(0.0, settings->backlashYEndMm());
    const double xErrorNearMm = qMax(0.0, settings->xErrorNearMm());
    const double xErrorFarMm = qMax(0.0, settings->xErrorMm());
    const double yErrorNearMm = qMax(0.0, settings->yErrorNearMm());
    const double yErrorFarMm = qMax(0.0, settings->yErrorMm());
    const double axisEpsMm = 1e-6;
    double pendingCompX = 0.0;
    double pendingCompY = 0.0;
    int lastDirX = 0;
    int lastDirY = 0;

    auto samePoint = [](const QPointF &a, const QPointF &b) {
        return QLineF(a, b).length() <= 1e-6;
    };
    auto dirFromDelta = [&](double d) {
        if (d > axisEpsMm) return 1;
        if (d < -axisEpsMm) return -1;
        return 0;
    };
    auto effectiveErrorMm = [&](double absYmm) {
        const double effX = qMax(0.0, interpolateByY(absYmm, yStartMm, yEndMm, xErrorNearMm, xErrorFarMm));
        const double effY = qMax(0.0, interpolateByY(absYmm, yStartMm, yEndMm, yErrorNearMm, yErrorFarMm));
        return QPointF(effX, effY);
    };
    auto currentEffectiveError = [&]() {
        const double absYmm = hasPos ? qAbs(currentPosMm.y()) : 0.0;
        return effectiveErrorMm(absYmm);
    };
    auto preloadHalfError = [&]() {
        const QPointF eff = currentEffectiveError();
        pendingCompX = qMax(pendingCompX, eff.x() * 0.5);
        pendingCompY = qMax(pendingCompY, eff.y() * 0.5);
    };
    auto applyReversalComp = [&](const QPointF &nominalToMm) {
        if (!hasPos) return nominalToMm;
        QPointF correctedToMm = nominalToMm;
        const double absYmm = qAbs((currentPosMm.y() + nominalToMm.y()) * 0.5);
        const QPointF eff = effectiveErrorMm(absYmm);
        const double effX = eff.x();
        const double effY = eff.y();
        pendingCompX = qMin(pendingCompX, effX);
        pendingCompY = qMin(pendingCompY, effY);

        int dirX = dirFromDelta(nominalToMm.x() - currentPosMm.x());
        if (dirX != 0) {
            if (lastDirX != 0 && dirX != lastDirX && pendingCompX > axisEpsMm) {
                correctedToMm.setX(correctedToMm.x() + dirX * pendingCompX);
                pendingCompX = 0.0;
            }
            const double movedX = correctedToMm.x() - currentPosMm.x();
            dirX = dirFromDelta(movedX);
            if (dirX != 0) {
                lastDirX = dirX;
                pendingCompX = qMin(effX, pendingCompX + qAbs(movedX));
            }
        }

        int dirY = dirFromDelta(nominalToMm.y() - currentPosMm.y());
        if (dirY != 0) {
            if (lastDirY != 0 && dirY != lastDirY && pendingCompY > axisEpsMm) {
                correctedToMm.setY(correctedToMm.y() + dirY * pendingCompY);
                pendingCompY = 0.0;
            }
            const double movedY = correctedToMm.y() - currentPosMm.y();
            dirY = dirFromDelta(movedY);
            if (dirY != 0) {
                lastDirY = dirY;
                pendingCompY = qMin(effY, pendingCompY + qAbs(movedY));
            }
        }

        return correctedToMm;
    };
    auto ensurePenUp = [&]() {
        if (!penIsDown) return;
        lines << QStringLiteral("G0 Z%1").arg(fmtMm(penUpZ));
        penIsDown = false;
    };
    auto ensurePenDown = [&]() {
        if (penIsDown) return;
        lines << QStringLiteral("G0 Z%1").arg(fmtMm(penDownZ));
        penIsDown = true;
        preloadHalfError();
    };
    auto moveRapid = [&](const QPointF &toMm) {
        if (hasPos && samePoint(currentPosMm, toMm)) return;
        ensurePenUp();
        const QPointF correctedToMm = applyReversalComp(toMm);
        if (hasPos && samePoint(currentPosMm, correctedToMm)) return;
        lines << xyLine("G0", correctedToMm.x(), correctedToMm.y());
        currentPosMm = correctedToMm;
        hasPos = true;
        hasMotion = true;
    };
    auto moveDraw = [&](const QPointF &toMm) {
        if (hasPos && samePoint(currentPosMm, toMm)) return;
        ensurePenDown();
        const QPointF correctedToMm = applyReversalComp(toMm);
        if (hasPos && samePoint(currentPosMm, correctedToMm)) return;
        lines << xyLine("G1", correctedToMm.x(), correctedToMm.y());
        currentPosMm = correctedToMm;
        hasPos = true;
        hasMotion = true;
    };

    auto markPageStart = [&](int pageIndex) {
        if (pageIndex < 0 || pageIndex >= pageCount) return;
        if (out.pageLineStart[pageIndex] >= 0) return;
        out.pageLineStart[pageIndex] = lines.size();
        lines << QStringLiteral("; PAGE %1").arg(pageIndex);
    };

    for (const PathSegment &seg : path.segments) {
        if (segmentLengthCm(seg) <= 1e-9) continue;
        const QVector<QPointF> &pts = seg.pointsCm;
        if (pts.size() < 2) continue;

        if (!seg.travel)
            markPageStart(seg.pageIndex);

        if (seg.travel) {
            const QPointF p0 = layoutCmToMachineMm(pts[0]);
            const QPointF p1 = layoutCmToMachineMm(pts[1]);
            const double travelLenMm = QLineF(p0, p1).length();
            const bool isJoinMove = travelLenMm <= joinDistMm + 1e-6;
            if (isJoinMove) {
                if (!hasPos || !samePoint(currentPosMm, p0)) moveRapid(p0);
                moveDraw(p1);
            } else {
                moveRapid(p0);
                moveRapid(p1);
            }
        } else {
            const QPointF p0 = layoutCmToMachineMm(pts[0]);
            if (!hasPos) {
                moveRapid(p0);
            } else if (!samePoint(currentPosMm, p0)) {
                const double gapMm = QLineF(currentPosMm, p0).length();
                if (gapMm <= joinDistMm + 1e-6) moveDraw(p0);
                else moveRapid(p0);
            }
            ensurePenDown();
            for (int i = 1; i < pts.size(); ++i) {
                const QPointF p = layoutCmToMachineMm(pts[i]);
                moveDraw(p);
            }
        }
    }

    if (!hasMotion) {
        out.gcode = QStringLiteral("; No drawable strokes\n");
        return out;
    }

    ensurePenUp();
    lines << QStringLiteral("G0 X0 Y0");

    if (out.pageLineStart[0] < 0)
        out.pageLineStart[0] = 7;

    int lastKnown = out.pageLineStart[0];
    for (int p = 1; p < pageCount; ++p) {
        if (out.pageLineStart[p] < 0)
            out.pageLineStart[p] = lastKnown;
        else
            lastKnown = out.pageLineStart[p];
    }

    out.gcode = lines.join(QLatin1Char('\n')) + QLatin1Char('\n');
    return out;
}

QString GcodeGenerator::generateSinglePage(const PathBuildResult &path, int pageIndex,
                                           const AppSettings *settings) {
    if (!settings) return QStringLiteral("; No settings\n");

    // Page-local CNC origin is page top-left in writer coordinates.
    const QPointF plotOriginCm(0, pageIndex * settings->pageHeightCm());
    PathBuildResult pagePath;
    bool sawFirstInk = false;
    for (const PathSegment &seg : path.segments) {
        if (seg.pageIndex != pageIndex) continue;
        PathSegment copy = seg;
        for (QPointF &pt : copy.pointsCm)
            pt -= plotOriginCm;
        const double len = segmentLengthCm(copy);
        if (len <= 1e-9) continue;
        // Drop cross-page connector travel that may be tagged with this page.
        // For standalone page output, we only start once first ink segment begins.
        if (copy.travel && !sawFirstInk) continue;
        if (!copy.travel) sawFirstInk = true;
        pagePath.segments.push_back(copy);
        pagePath.totalLengthCm += len;
    }

    if (pagePath.segments.isEmpty())
        return QStringLiteral("; No strokes on page %1\n").arg(pageIndex);

    return generate(pagePath, settings);
}
