#include "GcodeGenerator.h"

#include <QLineF>
#include <QPointF>
#include <QStringList>
#include <QtMath>

namespace {
QString fmtMm(double v) {
    return QString::number(v, 'f', 3);
}

QString xyLine(const char *cmd, double xMm, double yMm) {
    return QStringLiteral("%1 X%2 Y%3").arg(QLatin1String(cmd), fmtMm(xMm), fmtMm(yMm));
}

// App layout uses +X right, +Y down (cm). This machine expects GRBL X = layout Y, GRBL Y = layout X.
QPointF layoutCmToMachineMm(const QPointF &pCm) {
    return QPointF(pCm.y() * 10.0, pCm.x() * 10.0);
}

double segmentLengthCm(const PathSegment &seg) {
    const QVector<QPointF> &pts = seg.pointsCm;
    if (pts.size() < 2) return 0;
    if (seg.travel) return QLineF(pts[0], pts[1]).length();
    double len = 0;
    for (int i = 1; i < pts.size(); ++i)
        len += QLineF(pts[i - 1], pts[i]).length();
    return len;
}
}

QString GcodeGenerator::generate(const PathBuildResult &path, const AppSettings *settings) {
    if (!settings) return QStringLiteral("; No settings\n");

    const double penUpZ = settings->penUpZ();
    const double penDownZ = settings->penDownZ();
    const int feed = qMax(1, int(qRound(settings->feedRateMmPerMin())));

    QStringList lines;
    lines << QStringLiteral("; GRBL 1.1h — generated by WriterQt");
    lines << QStringLiteral("; Units: mm, absolute positioning");
    lines << QStringLiteral("G21");
    lines << QStringLiteral("G90");
    lines << QStringLiteral("G0 X0 Y0");
    lines << QStringLiteral("G0 Z%1").arg(fmtMm(penUpZ));
    lines << QStringLiteral("F%1").arg(feed);

    bool hasMotion = false;
    for (const PathSegment &seg : path.segments) {
        if (segmentLengthCm(seg) <= 1e-9) continue;
        const QVector<QPointF> &pts = seg.pointsCm;
        if (pts.size() < 2) continue;

        if (seg.travel) {
            const QPointF p0 = layoutCmToMachineMm(pts[0]);
            const QPointF p1 = layoutCmToMachineMm(pts[1]);
            lines << QStringLiteral("G0 Z%1").arg(fmtMm(penUpZ));
            lines << xyLine("G0", p0.x(), p0.y());
            lines << xyLine("G0", p1.x(), p1.y());
            hasMotion = true;
        } else {
            const QPointF p0 = layoutCmToMachineMm(pts[0]);
            lines << QStringLiteral("G0 Z%1").arg(fmtMm(penUpZ));
            lines << xyLine("G0", p0.x(), p0.y());
            lines << QStringLiteral("G0 Z%1").arg(fmtMm(penDownZ));
            for (int i = 1; i < pts.size(); ++i) {
                const QPointF p = layoutCmToMachineMm(pts[i]);
                lines << xyLine("G1", p.x(), p.y());
            }
            hasMotion = true;
        }
    }

    if (!hasMotion) {
        return QStringLiteral("; No drawable strokes\n");
    }

    lines << QStringLiteral("G0 Z%1").arg(fmtMm(penUpZ));
    lines << QStringLiteral("G0 X0 Y0");
    return lines.join(QLatin1Char('\n')) + QLatin1Char('\n');
}
